export enum ERROR_TYPES {
    USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST',
    UNAUTHORIZED = 'UNAUTHORIZED',
    DB_NOT_CONNECTED = 'DB_NOT_CONNECTED',
    GENERIC_ERROR = 'GENERIC_ERROR',
    LECTURE_NOT_FOUND = 'LECTURE_NOT_FOUND',
    CONTENT_GENERATION = 'CONTENT_GENERATION',
    'Not Found' = 'Not Found',
    BAD_REQUEST = 'BAD_REQUEST',
    CONFLICT_ERROR = 'CONFLICT_ERROR',
}
